// Generated by scripts/build.js. Edit files in src/ instead.
// Public API: pinByUnderline()

(function () {
    'use strict';

    function createMeikyoNichihanAdapter() {
        const dictionaryName = '明鏡日汉双解辞典';

        function hasNum(element) {
            return element.matches('div[data-sc-class="def1"]') &&
                (element.querySelector('span[data-sc-class="num"]') ||
                    element.querySelector('span[data-sc-class="num_circle"]') ||
                    element.querySelector('div[data-sc-class="num"]') ||
                    element.querySelector('div[data-sc-class="num_circle"]'));
        }

        function isDef0(element) {
            return element.matches('div[data-sc-class="def0"]');
        }

        function hasAncestorDef0(element) {
            let ancestorCheck = element.previousElementSibling;

            while (ancestorCheck) {
                if (isDef0(ancestorCheck)) {
                    return true;
                } else if (ancestorCheck.matches('div[data-sc-class="def1"]')) {
                    ancestorCheck = ancestorCheck.previousElementSibling;
                } else {
                    break;
                }
            }
            return false;
        }

        function collectSubDefs(startIndex, fullBlockElements) {
            const subDefs = [];
            for (let i = startIndex + 1; i < fullBlockElements.length; i++) {
                const el = fullBlockElements[i];
                if (el.matches('div[data-sc-class="def1"]') && !hasNum(el)) {
                    subDefs.push(el);
                } else {
                    break;
                }
            }
            return subDefs;
        }

        function prioritizeTarget(targetDef, subDefs) {
            const targetInSubDefs = subDefs.indexOf(targetDef);
            if (targetInSubDefs > 0) {
                subDefs.splice(targetInSubDefs, 1);
                subDefs.unshift(targetDef);
            }
        }

        function getTargetDef(underlinedElement) {
            const targetDef = underlinedElement.closest('div[data-sc-class="def1"]');
            if (!targetDef) return null;

            const parentLi = targetDef.closest('li[data-dictionary]');
            if (!parentLi || parentLi.getAttribute('data-dictionary') !== dictionaryName) {
                return null;
            }

            return targetDef;
        }

        function canHandle(context) {
            const targetDef = getTargetDef(context.underlinedElement);
            return Boolean(targetDef && targetDef.closest('div[data-sc-class="mjrhsjcd-entry"]'));
        }

        function pin(context) {
            const targetDef = getTargetDef(context.underlinedElement);
            if (!targetDef) return;

            const entryContainer = targetDef.closest('div[data-sc-class="mjrhsjcd-entry"]');
            if (!entryContainer) return;

            let blockStartElement = targetDef;
            let current = targetDef.previousElementSibling;
            const targetHasNum = hasNum(targetDef);

            if (targetHasNum) {
                while (current) {
                    if (isDef0(current)) {
                        blockStartElement = current;
                        break;
                    } else if (hasNum(current)) {
                        if (!hasAncestorDef0(current)) {
                            break;
                        }
                    }
                    current = current.previousElementSibling;
                }
            } else {
                let firstDef1WithNum = null;

                while (current) {
                    if (isDef0(current)) {
                        blockStartElement = current;
                        break;
                    } else if (hasNum(current)) {
                        if (!firstDef1WithNum) {
                            firstDef1WithNum = current;
                        }
                    }
                    current = current.previousElementSibling;
                }

                if (blockStartElement === targetDef && firstDef1WithNum) {
                    blockStartElement = firstDef1WithNum;
                }
            }

            const fullBlockElements = [blockStartElement];
            let nextInBlock = blockStartElement.nextElementSibling;
            const isBlockStartedByDef0 = isDef0(blockStartElement);

            while (nextInBlock) {
                if (isBlockStartedByDef0) {
                    if (isDef0(nextInBlock)) {
                        break;
                    }
                } else if (hasNum(nextInBlock)) {
                    break;
                }
                fullBlockElements.push(nextInBlock);
                nextInBlock = nextInBlock.nextElementSibling;
            }

            const nodesToMove = [];

            if (isDef0(blockStartElement)) {
                nodesToMove.push(blockStartElement);

                if (targetDef !== blockStartElement) {
                    const currentTargetHasNum = hasNum(targetDef);

                    if (!currentTargetHasNum) {
                        const targetIndex = fullBlockElements.indexOf(targetDef);
                        let mainDef = null;

                        for (let i = targetIndex - 1; i >= 1; i--) {
                            const el = fullBlockElements[i];
                            if (hasNum(el)) {
                                mainDef = el;
                                break;
                            }
                        }

                        if (mainDef) {
                            const mainDefIndex = fullBlockElements.indexOf(mainDef);
                            const subDefs = collectSubDefs(mainDefIndex, fullBlockElements);
                            prioritizeTarget(targetDef, subDefs);

                            const otherParts = fullBlockElements.filter(el =>
                                el !== blockStartElement && el !== mainDef && !subDefs.includes(el)
                            );

                            nodesToMove.push(mainDef);
                            nodesToMove.push(...subDefs);
                            nodesToMove.push(...otherParts);
                        } else {
                            const beforeTarget = fullBlockElements.slice(1, targetIndex);
                            const afterTarget = fullBlockElements.slice(targetIndex + 1);

                            nodesToMove.push(...beforeTarget);
                            nodesToMove.push(targetDef);
                            nodesToMove.push(...afterTarget);
                        }
                    } else {
                        const blockBody = fullBlockElements.slice(1);
                        const preamble = [];
                        const numberedGroups = [];
                        let bodyIndex = 0;

                        while (bodyIndex < blockBody.length) {
                            const element = blockBody[bodyIndex];

                            if (hasNum(element)) {
                                const group = [element];
                                bodyIndex++;

                                while (
                                    bodyIndex < blockBody.length &&
                                    blockBody[bodyIndex].matches('div[data-sc-class="def1"]') &&
                                    !hasNum(blockBody[bodyIndex])
                                ) {
                                    group.push(blockBody[bodyIndex]);
                                    bodyIndex++;
                                }

                                numberedGroups.push(group);
                            } else {
                                if (numberedGroups.length === 0) {
                                    preamble.push(element);
                                } else {
                                    numberedGroups[numberedGroups.length - 1].push(element);
                                }
                                bodyIndex++;
                            }
                        }

                        const targetGroupIndex = numberedGroups.findIndex(group => group.includes(targetDef));

                        if (targetGroupIndex !== -1) {
                            const included = new Set(nodesToMove);

                            for (const element of preamble) {
                                if (!included.has(element)) {
                                    nodesToMove.push(element);
                                    included.add(element);
                                }
                            }

                            const targetGroup = numberedGroups[targetGroupIndex];
                            for (const element of targetGroup) {
                                if (!included.has(element)) {
                                    nodesToMove.push(element);
                                    included.add(element);
                                }
                            }

                            numberedGroups.forEach((group, index) => {
                                if (index === targetGroupIndex) return;
                                for (const element of group) {
                                    if (!included.has(element)) {
                                        nodesToMove.push(element);
                                        included.add(element);
                                    }
                                }
                            });

                            for (const element of blockBody) {
                                if (!included.has(element)) {
                                    nodesToMove.push(element);
                                    included.add(element);
                                }
                            }
                        } else {
                            const targetIndex = fullBlockElements.indexOf(targetDef);
                            const beforeTarget = fullBlockElements.slice(1, targetIndex);
                            const afterTarget = fullBlockElements.slice(targetIndex + 1);

                            const beforeTargetWithoutNum = beforeTarget.filter(el => !hasNum(el));
                            const beforeTargetWithNum = beforeTarget.filter(el => hasNum(el));

                            nodesToMove.push(...beforeTargetWithoutNum);
                            nodesToMove.push(targetDef);
                            nodesToMove.push(...beforeTargetWithNum);
                            nodesToMove.push(...afterTarget);
                        }
                    }
                }
            } else if (!hasNum(targetDef)) {
                const mainDef = blockStartElement;
                const mainDefIndex = fullBlockElements.indexOf(mainDef);
                const subDefs = collectSubDefs(mainDefIndex, fullBlockElements);
                prioritizeTarget(targetDef, subDefs);

                const otherParts = fullBlockElements.filter(el =>
                    el !== mainDef && !subDefs.includes(el)
                );

                nodesToMove.push(mainDef);
                nodesToMove.push(...subDefs);
                nodesToMove.push(...otherParts);
            } else {
                const otherParts = fullBlockElements.filter(el =>
                    el !== blockStartElement && el !== targetDef
                );

                nodesToMove.push(blockStartElement);
                nodesToMove.push(targetDef);
                nodesToMove.push(...otherParts);
            }

            context.highlightElement(targetDef);

            let insertionPoint = null;
            const allDefs = entryContainer.querySelectorAll('div[data-sc-class="def0"], div[data-sc-class="def1"]');
            for (const def of allDefs) {
                if (isDef0(def) || hasNum(def)) {
                    insertionPoint = def;
                    break;
                }
            }

            if (insertionPoint) {
                if (insertionPoint === blockStartElement) {
                    if (nodesToMove.length > 1) {
                        let lastNode = nodesToMove[0];
                        for (let index = 1; index < nodesToMove.length; index++) {
                            const currentNode = nodesToMove[index];
                            if (currentNode.previousElementSibling !== lastNode) {
                                lastNode.after(currentNode);
                            }
                            lastNode = currentNode;
                        }
                    }
                } else {
                    insertionPoint.before(...nodesToMove);
                }
            }

            context.moveDictionaryToTop(targetDef);
        }

        return {
            name: 'meikyo-nichihan',
            canHandle,
            pin
        };
    }

    function createMeikyoKokugoV3Adapter() {
        const dictionaryName = '明鏡国語辞典 第三版';

        function getTargetMeaning(underlinedElement) {
            const targetMeaning = underlinedElement.closest(
                'div[data-sc-meaning][data-sc-class="level0"], div[data-sc-meaning][data-sc-class="level1"]'
            );
            if (!targetMeaning) return null;

            const parentLi = targetMeaning.closest('li[data-dictionary]');
            if (!parentLi || parentLi.getAttribute('data-dictionary') !== dictionaryName) {
                return null;
            }

            return targetMeaning;
        }

        function isLevel0(element) {
            return element.matches('div[data-sc-meaning][data-sc-class="level0"]');
        }

        function isLevel1(element) {
            return element.matches('div[data-sc-meaning][data-sc-class="level1"]');
        }

        function isEntryTail(element) {
            if (element.matches('div[data-sc-ruigo_items], div[data-sc-class="ruigo-items"]')) {
                return true;
            }

            return element.matches('div[data-sc-sanko], div[data-sc-class="sanko"]') &&
                Boolean(element.querySelector('[data-sc-kakiwake]'));
        }

        function isShikiri(element) {
            return element.matches('div[data-sc-shikiri], div[data-sc-class="shikiri"]');
        }

        function getBody(targetMeaning) {
            return targetMeaning.closest('div[data-sc-body]');
        }

        function collectMeaningGroup(targetMeaning) {
            const nodes = [targetMeaning];
            let next = targetMeaning.nextElementSibling;

            while (next && next.matches('div[data-sc-example]')) {
                nodes.push(next);
                next = next.nextElementSibling;
            }

            return nodes;
        }

        function collectLevel0Group(targetMeaning) {
            const nodes = [targetMeaning];
            let next = targetMeaning.nextElementSibling;

            while (next && !isLevel0(next) && !isEntryTail(next)) {
                nodes.push(next);
                next = next.nextElementSibling;
            }

            return nodes;
        }

        function findLevel0InsertionPoint(body, targetLevel0) {
            let insertionPoint = body.querySelector('div[data-sc-meaning][data-sc-class="level0"]');
            if (!insertionPoint) return null;
            if (insertionPoint === targetLevel0) return targetLevel0;

            let previous = insertionPoint.previousElementSibling;
            while (previous && isShikiri(previous)) {
                insertionPoint = previous;
                previous = previous.previousElementSibling;
            }

            return insertionPoint;
        }

        function findOwningLevel0(targetMeaning) {
            if (isLevel0(targetMeaning)) {
                return targetMeaning;
            }

            let current = targetMeaning.previousElementSibling;

            while (current) {
                if (isLevel0(current)) {
                    return current;
                }
                current = current.previousElementSibling;
            }

            return null;
        }

        function findLevel1InsertionPoint(body, targetMeaning) {
            const owningLevel0 = findOwningLevel0(targetMeaning);
            let current = owningLevel0 ? owningLevel0.nextElementSibling : body.firstElementChild;

            while (current && !isLevel0(current)) {
                if (isLevel1(current)) {
                    return current;
                }
                current = current.nextElementSibling;
            }

            return null;
        }

        function setImportantStyle(element, property, value) {
            if (element) {
                element.style.setProperty(property, value, 'important');
            }
        }

        function normalizeLeadingGaiji(targetMeaning) {
            if (!isLevel0(targetMeaning)) return;

            const leadingGaiji = targetMeaning.firstElementChild;
            if (!leadingGaiji || !leadingGaiji.matches('[data-sc-img][data-sc-gaiji]')) return;

            const image = leadingGaiji.querySelector('img');
            if (!image) return;

            const imageLink = leadingGaiji.querySelector('.gloss-image-link') || image.closest('a');
            const imageContainer = leadingGaiji.querySelector('.gloss-image-container') || image.parentElement;

            setImportantStyle(leadingGaiji, 'display', 'inline-block');
            setImportantStyle(leadingGaiji, 'width', '1em');
            setImportantStyle(leadingGaiji, 'height', '1em');
            setImportantStyle(leadingGaiji, 'line-height', '1');
            setImportantStyle(leadingGaiji, 'vertical-align', '-0.12em');
            setImportantStyle(leadingGaiji, 'margin-right', '0.15em');

            setImportantStyle(imageLink, 'display', 'inline-block');
            setImportantStyle(imageLink, 'width', '1em');
            setImportantStyle(imageLink, 'height', '1em');
            setImportantStyle(imageLink, 'max-width', '1em');
            setImportantStyle(imageLink, 'line-height', '1');
            setImportantStyle(imageLink, 'vertical-align', 'middle');

            setImportantStyle(imageContainer, 'width', '1em');
            setImportantStyle(imageContainer, 'height', '1em');
            setImportantStyle(imageContainer, 'max-width', '1em');
            setImportantStyle(imageContainer, 'max-height', '1em');
            setImportantStyle(imageContainer, 'font-size', '1em');
            setImportantStyle(imageContainer, 'line-height', '1');
            setImportantStyle(imageContainer, 'vertical-align', 'middle');
        }

        function canHandle(context) {
            const targetMeaning = getTargetMeaning(context.underlinedElement);
            return Boolean(targetMeaning && getBody(targetMeaning));
        }

        function pinLevel0(context, body, targetMeaning) {
            const nodesToMove = collectLevel0Group(targetMeaning);
            const insertionPoint = findLevel0InsertionPoint(body, targetMeaning);

            normalizeLeadingGaiji(targetMeaning);
            context.highlightElement(targetMeaning);

            if (insertionPoint && insertionPoint !== targetMeaning) {
                insertionPoint.before(...nodesToMove);
            }
        }

        function pinLevel1(context, body, targetMeaning) {
            const owningLevel0 = findOwningLevel0(targetMeaning);
            if (!owningLevel0) return;

            const meaningNodes = collectMeaningGroup(targetMeaning);
            const level1InsertionPoint = findLevel1InsertionPoint(body, targetMeaning);

            context.highlightElement(targetMeaning);

            if (level1InsertionPoint && level1InsertionPoint !== targetMeaning) {
                level1InsertionPoint.before(...meaningNodes);
            }

            const level0Nodes = collectLevel0Group(owningLevel0);
            const level0InsertionPoint = findLevel0InsertionPoint(body, owningLevel0);

            normalizeLeadingGaiji(owningLevel0);

            if (level0InsertionPoint && level0InsertionPoint !== owningLevel0) {
                level0InsertionPoint.before(...level0Nodes);
            }
        }

        function pin(context) {
            const targetMeaning = getTargetMeaning(context.underlinedElement);
            if (!targetMeaning) return;

            const body = getBody(targetMeaning);
            if (!body) return;

            if (isLevel0(targetMeaning)) {
                pinLevel0(context, body, targetMeaning);
            } else {
                pinLevel1(context, body, targetMeaning);
            }

            context.moveDictionaryToTop(targetMeaning);
        }

        return {
            name: 'meikyo-kokugo-v3',
            canHandle,
            pin
        };
    }

    function pinByUnderline() {
        const glossary = document.querySelector('.yomitan-glossary');
        if (!glossary) return;

        const underlinedElement = glossary.querySelector('u');
        if (!underlinedElement) return;

        const highlightClassName = 'pin-by-underline-highlight';

        function ensureHighlightStyles() {
            const styleId = 'pin-by-underline-highlight-styles';
            if (document.getElementById(styleId)) return;

            const styleElement = document.createElement('style');
            styleElement.id = styleId;
            styleElement.textContent = `
    .${highlightClassName} {
        background-color: #fff2a8 !important;
    }

    .nightMode .${highlightClassName},
    .night_mode .${highlightClassName},
    .night-mode .${highlightClassName} {
        background-color: #000000 !important;
    }
    `;
            document.head.appendChild(styleElement);
        }

        const context = {
            glossary,
            underlinedElement,
            highlightElement(element) {
                ensureHighlightStyles();
                element.classList.add(highlightClassName);
            },
            moveDictionaryToTop(element) {
                const parentLi = element.closest('li[data-dictionary]');
                if (parentLi && parentLi.parentElement) {
                    parentLi.parentElement.prepend(parentLi);
                }
            }
        };

        const adapters = [
            createMeikyoNichihanAdapter(),
            createMeikyoKokugoV3Adapter()
        ];

        for (const adapter of adapters) {
            if (adapter.canHandle(context)) {
                adapter.pin(context);
                return;
            }
        }
    }

    const root = typeof globalThis !== 'undefined' ? globalThis : window;
    root.pinByUnderline = pinByUnderline;
    if (typeof window !== 'undefined') {
        window.pinByUnderline = pinByUnderline;
    }
})();
