const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const sourceFiles = [
    'src/adapters/meikyo-nichihan.js',
    'src/adapters/meikyo-kokugo-v3.js',
    'src/core.js'
];

const header = `// Generated by scripts/build.js. Edit files in src/ instead.
// Public API: pinByUnderline()

`;

const body = sourceFiles
    .map(file => fs.readFileSync(path.join(rootDir, file), 'utf8').trimEnd())
    .join('\n\n');

const indentedBody = body
    .split('\n')
    .map(line => line ? `    ${line}` : '')
    .join('\n');

const output = `${header}(function () {
    'use strict';

${indentedBody}

    const root = typeof globalThis !== 'undefined' ? globalThis : window;
    root.pinByUnderline = pinByUnderline;
    if (typeof window !== 'undefined') {
        window.pinByUnderline = pinByUnderline;
    }
})();
`;

fs.writeFileSync(path.join(rootDir, 'script.js'), output, 'utf8');
console.log('Built script.js from src/');
